
name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Lấy mã nguồn từ kho lưu trữ (Checkout repository)
      uses: actions/checkout@v3

    - name: Cài đặt Node.js môi trường
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Cài đặt các thư viện (bao gồm Jest)
      run: npm install

    - name: Chạy Unit Test
      run: npm test
